### ISSUE TITLE
TypeError: sequence item 0: expected str instance, tuple found

### ISSUE THREAD

**Issue by DarkAlchy** [noembryo/ComfyUI-noEmbryo#5]
No matter what I give it (string, text, etc...) I get this error about it being a tuple .  edit: This is for the regex node.

**Comment by noembryo** [comment]
Another ComfyUI change, another bug.. 😉 
Hopefully fixed with the 1.0.4 version of the nodes.
Thanks for the heads up. 🙏

**Comment by DarkAlchy** [comment]
Fixed, thank you.
