### ISSUE TITLE
workflow?

### ISSUE THREAD

**Issue by offmybach** [noembryo/ComfyUI-noEmbryo#6]
I've read some great things about your nodes but am unable to find any workflows incorporating them so that I can see connections from and to. Would you be so kind as to link to some workflows that you've created using the term list node? Someone had gotten, by mistake, consistent characters in different poses. I'd like to give that a try. He accidentally posted pasted the .json list by mistake into the positive prompt.

**Comment by noembryo** [comment]
> I've read some great things about your nodes but am unable to find any workflows incorporating them so that I can see connections from and to. Would you be so kind as to link to some workflows that you've created using the term list node? 

I use them in all my workflows, but the workflows themselves are too complicated to post here.
OTOH, the PromptTermList nodes are really simple.
They just produce some text, depending on the terms that you have saved in your TermList files.

In this [Example.zip](https://github.com/user-attachments/files/17512059/Example.zip), there is a minimal workflow that uses 3 PromptTermLists.
You must copy the `TermList1.json`, `TermList2.json` and `TermList3.json` file to the TermLists directory that it's inside the "ComfyUI\custom_nodes\ComfyUI-noEmbryo" folder (replace the existing files) and refresh your browser (hit F5).
>Someone had gotten, by mistake, consistent characters in different poses. I'd like to give that a try. He accidentally posted pasted the .json list by mistake into the positive prompt.

This is not the way to use them 😜, but I'm curious about what this could achieve.. 🤔
